#!/bin/bash
echo running t1
nc -C localhost 6667 << 'EOF'
PASS PASS
USER FIRST 0 * FIRST
NICK First
JOIN #CHANNEL
TOPIC
TOPIC 
TOPIC CHANNEL
TOPIC #CHANNEL
TOPIC CHANNEL THIS_IS_invalid_TOPIC
TOPIC #CHANNEL
TOPIC #CHANNEL THIS_IS_NEW_TOPIC
TOPIC #CHANNEL
TOPIC #CHANNEL :THIS_IS_another_NEW_TOPIC
TOPIC #CHANNEL
TOPIC #CHANNEL :
TOPIC #CHANNEL
TOPIC #CHANNEL newTopic
TOPIC #CHANNEL
EOF