#ifndef DEFINES_HPP	
# define DEFINES_HPP

#define RPL_WELCOME(nick, network) (":" + SERVERNAME + " 001 " + nick + " :Welcome to "+ network + ", " + nick)
#define RPL_YOURHOST (":" + SERVERNAME + " 002 :Your host is " + SERVERNAME + ", running version 1.0")
#define RPL_MYINFO(nick) (":" + SERVERNAME + " 004 " + nick + " 1.0 :Available user modes: io, channel modes: tkl")
#define RPL_CHANNELMODEIS(client, channel) (":" + SERVERNAME + " 324 " + client + " " + channel + " :Available user modes: io, channel modes: tkl")
#define RPL_TOPICWHOTIME(client, channel, author, setat) (":" + SERVERNAME + " 333 " + client + " " + channel + " " + author + " " + setat)
#define RPL_NOTOPIC(client, channel) (":" + SERVERNAME + " 331 " + client + " " + channel + " :No topic is set")
#define RPL_TOPIC(client, channel, topic) (":" + SERVERNAME + " 332 " + client + " " + channel + " " + topic)
#define RPL_INVITING(client, nick, channel) (":" + SERVERNAME + " 341 " + client + " " + nick + " :" + channel)
#define RPL_NAMREPLY(nick, channel, users) (":" + SERVERNAME + " 353 " + nick + " = " + channel + " :" + users + "")
#define RPL_MOTD(nick, motd) (":" + SERVERNAME + " 372 " + nick + ":- " + motd)
#define RPL_MOTDSTART(nick, server) (":" + SERVERNAME + " 375 " + nick + " :- " + server + " Message of the day - ")
#define RPL_ENDOFMOTD(nick) (":" + SERVERNAME + " 376 " + nick + ":End of /MOTD command.")

#define ERR_NOSUCHNICK(client, nick) (":" + SERVERNAME + " 401 " + client + " " + nick + " :No such nick")
#define ERR_UNKNOWNCOMMAND(client, command) (":" + SERVERNAME + " 421 " + client + " "  + command + " :Unknown command")
#define ERR_NONICKNAMEGIVEN() (":" + SERVERNAME + " 431 :No nickname given")
#define ERR_ERRONEUSNICKNAME(client, nick) (":" + SERVERNAME + " 432 " + client + " " + nick + " :Erroneus nickname")
#define ERR_NICKNAMEINUSE(client, nick) (":" + SERVERNAME + " 433 " + client + " " + nick + " :Nickname is already in use")
#define ERR_USERNOTINCHANNEL(client, nick, channel) (":" + SERVERNAME + " 441 " + client + " " + nick + " " + channel + " :They aren't on that channel")
#define ERR_NOTONCHANNEL(client, channel) (":" + SERVERNAME + " 442 " + client + " " + channel + " :You're not on that channel")
#define ERR_USERONCHANNEL(nick, channel) (":" + SERVERNAME + " 443 " + nick + " " + channel + " :is already on channel")
#define ERR_NOTREGISTERED(client) (":" + SERVERNAME + " 451 " + client + " :You are not registered")
#define ERR_NEEDMOREPARAMS(client, command) (":" + SERVERNAME + " 461 " + client + " " + command + " :Not enough parameters")
#define ERR_ALREADYREGISTERED(client) (":" + SERVERNAME + " 462 " + client + " :You may not reregister")
#define ERR_PASSWDMISMATCH(client) (":" + SERVERNAME + " 464 " + client + " :Password incorrect")
#define ERR_CHANNELISFULL(client, channel) (":" + SERVERNAME + " 471 " + client + " " + channel + " :Cannot join channel (+l)")
#define ERR_INVITEONLYCHAN(client, channel) (":" + SERVERNAME + " 473 " + client + " " + channel + " :Cannot join channel (+i)")
#define ERR_BADCHANNELKEY(client, channel) (":" + SERVERNAME + " 475 " + client + " " + channel + " :Cannot join channel (+k)")
#define ERR_BADCHANMASK(client, channel) (":" + SERVERNAME + " 476 " + client + " #" + channel + " :Bad Channel Mask")
#define ERR_CHANOPRIVSNEEDED(client, channel) (":" + SERVERNAME + " 482 " + client + " " + channel + " :You're not channel operator")
#define ERR_UMODEWUNKNOWNFLAG(flag) (":" + SERVERNAME + " 501 :Unknown MODE flag: " + flag)

#define INVITE(client, invited, channel) (":" + client + " INVITE " + invited + " " + channel)
#define JOIN(client, channel) (":" + client + " JOIN " + channel)
#define KICK(client, channel, kicked) (":" + client + " KICK " + channel + " " + kicked)
#define MODE1(client, channel, flag) (":" + client + " MODE " + channel + " " + flag)
#define MODE2(client, channel, flag, args) (":" + client + " MODE " + channel + " " + flag + " " + args)
#define PART(client, channel) (":" + client + " PART " + channel)
#define PRIVMSG(client, channel, message) (":" + client + " PRIVMSG " + channel + " " + message)
#define NICK(oldNick, newNick) (":" + oldNick + " NICK " + newNick)
#define TOPIC(client, channel, topic) (":" + client + " TOPIC " + channel + " :" + topic)

#endif
